import React from 'react';

const EB1A: React.FC = () => (
  <div className="bg-white min-h-screen text-left flex flex-col items-center py-10 px-4 pt-20">
    <div className="max-w-7xl w-full px-0 md:px-10">
      {/* BEGIN FULL PAGE CONTENT - copied from https://www.wegreened.com/EB1A */}
      <h1 className="text-3xl md:text-4xl font-extrabold text-[#0097b2] mb-4 leading-tight">EB1-A (Alien of Extraordinary Ability)</h1>
      <h2 className="text-2xl font-bold text-[#0097b2] mb-2">Introduction</h2>
      <p className="text-[21px] text-gray-700 mb-4">EB1-A or EB1-EA is a subgroup of first preference employment-based immigration (EB-1). North America Immigration Law Group specializes in EB1-A (Alien of Extraordinary Ability) petitions. This immigration preference category is for foreign nationals of extraordinary ability in the sciences, arts, education, business, or athletics. According to federal immigration law, such persons are not required to have a prospective employer (unlike EB1-B and EB1-C, and other preference categories), but they must be entering to continue to work in their chosen field, and they must substantially benefit prospectively in the U.S. In addition, the petitioner has to show that the foreign person sustained national or international acclaim with recognized achievements. This is the requirement that is most difficult to prove. Based on our experience, North America Immigration Law Group has developed winning strategy of argument to meet this prong of requirement. To win an extraordinary ability case requires extensive documentation and excellent petition skills of the attorney. You can trust North America Immigration Law Group with your EB1-A case.</p>
      <h2 className="text-2xl font-bold text-[#0097b2] mb-2">Advantages: No Labor Certification is Required, Self Petition is Allowed</h2>
      <p className="text-[21px] text-gray-700 mb-4">There are many advantages of the employment-based category EB1-A. First of all, a specific job offer is not required for a foreign person in this group, as long as the foreign person is entering the United States to continue work in the field in which he or she has extraordinary ability, therefore self-petition is allowed. Please note, the fact that self-petition is allowed does not mean you should choose a DIY petition. Petition for an immigration visa is a complicated process and you may want an immigration attorney to handle all the complicated legal and regulation issues. North America Immigration Law Group has filed countless successful EB1-A petitions for our clients.</p>
      <p className="text-[21px] text-gray-700 mb-4">Moreover, a labor certification not required. Obtaining a labor certification is a long process. EB1-A applications therefore save an applicant a lot of time. As a result, attorneys in North America Immigration Law Group encourage clients to petition for this classification if they are qualified.</p>
      <h2 className="text-2xl font-bold text-[#0097b2] mb-2">Qualifications of an EB1-A Petitioner</h2>
      <p className="text-[21px] text-gray-700 mb-4">In order to be qualified for an EB1-A visa, the petitioner must show: the foreign person has sustained national or international acclaims for his/her achievements, the foreign person is seeking to enter the United States to continue to work in the field of endeavor that is the subject of the acclaim, and the presence of the foreign person and his/her activity will benefit the United States. If you have questions about these three requirements, you may contact North America Immigration Law Group. Click here to read <a href="https://www.wegreened.com/EB1A_qualification" className="text-[#0097b2] underline">(Qualification of EB1A (Alien of Extraordinary Ability))</a>.</p>
      <h2 className="text-2xl font-bold text-[#0097b2] mb-2">Definitions and Evidence of “Extraordinary Ability“</h2>
      <p className="text-[21px] text-gray-700 mb-4">Federal regulations define “extraordinary ability“ as a level of expertise indicating the individual is one of a small percentage who have risen to the very top of a particular field in the sciences, arts, education, business, and athletics. The federal law indicates that such a person will have received national and international acclaim. National or international acclaims can be demonstrated by receipt of a major internationally recognized award such as Nobel Prize or the Academy Award. Alternatively, immigration law requires that the petitioner must provide at least three of the following types of evidence:</p>
      <ol className="list-decimal pl-8 text-gray-800 text-[21px] mb-6 space-y-1">
        <li>Receipt of lesser nationally or internationally recognized prizes or awards for excellence in the field of endeavor.</li>
        <li>Membership in an association that requires outstanding achievement as a condition of membership in the field for which the classification is sought</li>
        <li>Published material about the foreign person or his or her work in professional, trade journals, or major media publications. (These items must include title, date, author, and must be translated into English)</li>
        <li>The foreign person's participation, on a panel or individually, as a judge of the work of others in the same or a related field</li>
        <li>Evidence of original contributions, usually through publication, of major significance in the foreign national's fields of science, scholastic, artistic, or athletic</li>
        <li>Authorship of scholarly articles in the field, in professional journals, or other major media (national newspapers, magazines, etc.)</li>
        <li>Display of the foreign national's work at significant exhibitions</li>
        <li>Performance in a significant role for organizations or establishments that have a distinguished reputation</li>
        <li>Receipt of a higher salary or remuneration than is usual in the field</li>
        <li>Commercial success in the performing arts as shown by box office receipts or sales records, cassette, compact disk, or video sales, or</li>
        <li>Other comparable evidence if the above types of evidence do not readily apply to the foreign national's occupations</li>
      </ol>
      <p className="text-[21px] text-gray-700 mb-4">The meanings of these evidentiary criteria are ambiguous. Cases in front of AAO (Administrative Appeal Office) have indicated that not every criterion applies to every foreign beneficiary. Even immigration attorneys sometimes confuse which evidentiary criterion applies to their clients. North America Immigration Law Group can accurately distinguish which criterion applies to a client's application based on years of strict legal training and experience of our attorneys. Click here to read <a href="https://www.wegreened.com/EB1A_evidences" className="text-[#0097b2] underline">(Documentation of EB1-A (Alien of Extraordinary Ability) Petition)</a>.</p>
      <h2 className="text-2xl font-bold text-[#0097b2] mb-2">“Very top of the Endeavor“</h2>
      <p className="text-[21px] text-gray-700 mb-4">With regard to the requirement that the foreign person represents a “small percentage who has risen to the very top“ of the field of endeavor, AAO cases indicate that the actual field of endeavor must be defined before determining whether the foreign person has extraordinary ability in that field. North America Immigration Law Group is of the opinion that if the field is narrowly defined, it is more likely to argue that the foreign person has risen to the top of the field. In Victoria Chen's Blog article <a href="https://www.wegreened.com/Victoria-Immigration-Blog-We-Greened-Dot-Com-20110120" className="text-[#0097b2] underline">Have You Risen to the very Top of the Endeavor?</a> Ms. Chen explained that petitioners should take advantage of the foreign beneficiary's past education and working experience to define the field of endeavor. However, it is not true that the more narrow the field is defined, the more likely that the petition will be approved. Some AAO cases have pointed that the adjudicating officers get suspicious about cases in which the field is so narrowly defined that rising to the top of the endeavor is meaningless. To know more about how to define your field of endeavor, contact North America Immigration Law Group today.</p>
      <h2 className="text-2xl font-bold text-[#0097b2] mb-2">How to Present Evidence</h2>
      <p className="text-[21px] text-gray-700 mb-4">Attorneys of North America Immigration Law Group, are of the opinion that the best way to address the question whether the foreign person is “one of the small percentage who have risen to the very top“ of his or her field is to present evidence that provides a basis for comparison between the foreign person and those persons who are average or typical in the field. For example, if the foreign national is in a field in which publication of scholarly articles is typical, North America Immigration Law Group will present evidence that the client's articles have appeared in the most prestigious journals in the field, have been the subject of peer review in such journals, or have been widely cited in other scholarly articles.</p>
      <h2 className="text-2xl font-bold text-[#0097b2] mb-2">Comparing to Approved Cases</h2>
      <p className="text-[21px] text-gray-700 mb-4">Although USCIS tried to downplay comparison to other approved cases in the same field of endeavor, attorneys of North America Immigration Law Group have found that the court and AAO consistently stated that the agency rules themselves make comparison with others in the field the controlling standard for awarding extraordinary ability status. Therefore, how USCIS has treated other persons in the field with comparable qualifications is highly relevant to an extraordinary ability case.</p>
      <h2 className="text-2xl font-bold text-[#0097b2] mb-2">Two-Part Approach Taken by the USCIS Adjudicators</h2>
      <p className="text-[21px] text-gray-700 mb-4">In 2010, the U.S. Court of Appeals for the Ninth Circuit reviewed the denial of a petition filed under the classification of EB1-A, the Kazarian case. The AAO determines that Kazarian case sets forth a two-part approach : Part One: Counting the Types of Evidence Provided; Part Two: Final Merits Determination. Please click here to read the detailed introduction of this important case summarized by North America Immigration Law Group. <a href="https://www.wegreened.com/EB1A_twopart" className="text-[#0097b2] underline">Two-Part Approach (the Kazarian case) for EB1-A (Alien of Extraordinary Ability) petition</a></p>
      <p className="text-[21px] text-gray-700 mb-4">If you want to learn more about the first preference employment immigration summarized by North America Immigration Law Group, please click here. <a href="https://www.wegreened.com/eb1" className="text-[#0097b2] underline">Learn More About EB1: Comparison between Employment Based First Preferences EB1-A, EB1-B, and EB1-C (Priority Worker)</a></p>
      <h2 className="text-2xl font-bold text-[#0097b2] mb-2">Applying for Alien of Extraordinary Ability (EB1A) from outside of the U.S.</h2>
      <p className="text-[21px] text-gray-700 mb-4">Please <a href="https://www.wegreened.com/How-Can-I-get-a-Green-Card-Outside-the-US" className="text-[#0097b2] underline">Click Here</a> for more information regarding applying for Alien of Extraordinary Ability (EB1A) from outside of the U.S.</p>
      <ul className="pl-6 text-gray-800 space-y-1 text-[21px]">
        <li>EB1-A (Alien of Extraordinary Ability)</li>
        <li><a href="https://www.wegreened.com/EB1B-Outstanding-Professors-and-Researchers" className="text-[#0097b2] underline">(EB1-B or EB1-OR) Outstanding Professors and Researchers</a></li>
        <li><a href="https://www.wegreened.com/EB1C-Multinational-Executives-or-Managers" className="text-[#0097b2] underline">EB1-C Multinational Executives or Managers</a></li>
        <li><a href="https://www.wegreened.com/eb1" className="text-[#0097b2] underline">EB1 Visa Requirements</a></li>
        <li><a href="https://www.wegreened.com/EB1A_twopart" className="text-[#0097b2] underline">Two-Part Approach (the Kazarian case) for EB1-A (Alien of Extraordinary Ability) petition</a></li>
      </ul>
    </div>
  </div>
);

export default EB1A;
